#if !defined(AFX_AVVIEWX_H__EF950EC7_EF09_11D3_A484_00C04F6B9531__INCLUDED_)
#define AFX_AVVIEWX_H__EF950EC7_EF09_11D3_A484_00C04F6B9531__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAvViewX wrapper class

class CAvViewX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAvViewX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			//A662DA7E-CCB7-4743-B71A-D817F6D575DF - DWF Viewer control CLSID
			= {0xA662DA7E, 0xCCB7, 0x4743, {0xB7, 0x1A, 0xD8, 0x17, 0xF6, 0xD5, 0x75, 0xDF } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetSourcePath();
	void SetSourcePath(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AVVIEWX_H__EF950EC7_EF09_11D3_A484_00C04F6B9531__INCLUDED_)
