<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>Windows</MyType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutputPath>.\bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
	  <Reference Include="Autodesk.Inventor.Interop">
	    <SpecificVersion>False</SpecificVersion>
	    <EmbedInteropTypes>False</EmbedInteropTypes>
	    <HintPath Condition="Exists('$(programfiles)\Autodesk\Inventor OEM 2026\Bin')">$(programfiles)\Autodesk\Inventor OEM 2026\Bin\Autodesk.Inventor.Interop.dll</HintPath>
          <HintPath Condition="Exists('$(programfiles)\Autodesk\Inventor 2026\Bin')">$(programfiles)\Autodesk\Inventor 2026\Bin\Autodesk.Inventor.Interop.dll</HintPath>
          <HintPath Condition="Exists('..\..\..\Bin')">..\..\..\Bin\Autodesk.Inventor.Interop.dll</HintPath>
	    <HintPath Condition="Exists('..\..\..\InventorSDK\Source\DeveloperTools\References\primaryinterop\CurrentVersion')">..\..\..\InventorSDK\Source\DeveloperTools\References\primaryinterop\CurrentVersion\Autodesk.Inventor.Interop.dll</HintPath>
	    <HintPath Condition="Exists('..\..\..\..\References\PrimaryInterop\CurrentVersion')">..\..\..\..\References\PrimaryInterop\CurrentVersion\Autodesk.Inventor.Interop.dll</HintPath>
	    <EmbedInteropTypes>False</EmbedInteropTypes>
	    <Private>True</Private>
	  </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="clsCFSolveEvent.vb" />
    <Compile Update="FrmFeatureStatistics.Designer.vb">
      <DependentUpon>FrmFeatureStatistics.vb</DependentUpon>
    </Compile>
    <Compile Update="FrmFeatureStatistics.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="GetFeaturesInfo.vb" />
    <Compile Update="modUICustomization.vb" />
    <Compile Update="StandardAddInServer.vb" />
  </ItemGroup>
  <ItemGroup>
    <None Include="FeatureStatistics.X.manifest" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Autodesk.FeatureStatistics.Inventor.addin" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Readme.txt" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="My Project\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="FrmFeatureStatistics.resx">
      <DependentUpon>FrmFeatureStatistics.vb</DependentUpon>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <PropertyGroup>
    <ApplicationManifest>FeatureStatistics.X.manifest</ApplicationManifest>
  </PropertyGroup>
</Project>