// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "avviewx.h"

/////////////////////////////////////////////////////////////////////////////
// CAvViewX

IMPLEMENT_DYNCREATE(CAvViewX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAvViewX properties

/////////////////////////////////////////////////////////////////////////////
// CAvViewX operations

CString CAvViewX::GetSourcePath()
{
	CString result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CAvViewX::SetSourcePath(LPCTSTR lpszNewValue)
{
	static BYTE parms[] = VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, lpszNewValue);
}
