<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net8.0-windows</TargetFramework>
    <ProjectType>Local</ProjectType>
    <MyType>WindowsForms</MyType>
    <AssemblyName>CustomGraphics</AssemblyName>
	<AssemblyCompanyName>Autodesk, Inc.</AssemblyCompanyName>
    <OutputType>WinExe</OutputType>
    <StartupObject>CustomGraphics.frmLaserDrilling</StartupObject>
    <RootNamespace>CustomGraphics</RootNamespace>
	<OutputPath>.\bin\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<UseWindowsForms>True</UseWindowsForms>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
       <Reference Include="Autodesk.Inventor.Interop">
      <SpecificVersion>False</SpecificVersion>
      <EmbedInteropTypes>False</EmbedInteropTypes>
	  <HintPath Condition="Exists('$(programfiles)\Autodesk\Inventor OEM 2026\Bin')">$(programfiles)\Autodesk\Inventor OEM 2026\Bin\Autodesk.Inventor.Interop.dll</HintPath>
      <HintPath Condition="Exists('$(programfiles)\Autodesk\Inventor 2026\Bin')">$(programfiles)\Autodesk\Inventor 2026\Bin\Autodesk.Inventor.Interop.dll</HintPath>
      <HintPath Condition="Exists('..\..\..\Bin')">..\..\..\Bin\Autodesk.Inventor.Interop.dll</HintPath>
	  <HintPath Condition="Exists('..\..\..\InventorSDK\Source\DeveloperTools\References\primaryinterop\CurrentVersion')">..\..\..\InventorSDK\Source\DeveloperTools\References\primaryinterop\CurrentVersion\Autodesk.Inventor.Interop.dll</HintPath>
      <HintPath Condition="Exists('..\..\..\..\..\References\PrimaryInterop\CurrentVersion')">..\..\..\..\..\References\PrimaryInterop\CurrentVersion\Autodesk.Inventor.Interop.dll</HintPath>
	  <EmbedInteropTypes>False</EmbedInteropTypes>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Form1.Designer.vb">
      <SubType>Code</SubType>
      <DependentUpon>Form1.vb</DependentUpon>
    </Compile>
    <Compile Update="Form1.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Globals.vb">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="LaserPath.vb">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="LaserTool.vb">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="LaserTrace.vb">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="RemovedPart.vb">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Sparks.vb">
      <SubType>Code</SubType>
    </Compile>
    <EmbeddedResource Update="Form1.resX">
      <DependentUpon>Form1.vb</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
</Project>