<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
	<MyType>WindowsFormsWithCustomSubMain</MyType>
	<AssemblyName>AssemblyTree</AssemblyName>
	<RootNamespace>AssemblyTree</RootNamespace>
	<StartupObject>AssemblyTree.frmAssemblyTree</StartupObject>
    <OutputPath>.\bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<OutputType>WinExe</OutputType>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
	  <Reference Include="Autodesk.Inventor.Interop">
		  <SpecificVersion>False</SpecificVersion>
		  <EmbedInteropTypes>False</EmbedInteropTypes>
		  <HintPath Condition="Exists('$(programfiles)\Autodesk\Inventor OEM 2026\Bin')">$(programfiles)\Autodesk\Inventor OEM 2026\Bin\Autodesk.Inventor.Interop.dll</HintPath>
          <HintPath Condition="Exists('$(programfiles)\Autodesk\Inventor 2026\Bin')">$(programfiles)\Autodesk\Inventor 2026\Bin\Autodesk.Inventor.Interop.dll</HintPath>
          <HintPath Condition="Exists('..\..\..\Bin')">..\..\..\Bin\Autodesk.Inventor.Interop.dll</HintPath>
		  <HintPath Condition="Exists('..\..\..\InventorSDK\Source\DeveloperTools\References\primaryinterop\CurrentVersion')">..\..\..\InventorSDK\Source\DeveloperTools\References\primaryinterop\CurrentVersion\Autodesk.Inventor.Interop.dll</HintPath>
		  <HintPath Condition="Exists('..\..\..\..\..\References\PrimaryInterop\CurrentVersion')">..\..\..\..\..\References\PrimaryInterop\CurrentVersion\Autodesk.Inventor.Interop.dll</HintPath>
		  <EmbedInteropTypes>False</EmbedInteropTypes>
		  <Private>True</Private>
	  </Reference>
    <COMReference Include="stdole">
      <Guid>{00020430-0000-0000-C000-000000000046}</Guid>
      <VersionMajor>2</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>primary</WrapperTool>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="AssemblyTree.vb">
      <SubType>Form</SubType>
    </Compile>
    <EmbeddedResource Update="AssemblyTree.resx">
      <DependentUpon>AssemblyTree.vb</DependentUpon>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
</Project>